name: validate-main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Lint
      run: |
        sudo python -m pip install pip --upgrade pylint
        pylint magic_guid/__init__.py

    - name: Validate
      run: python magic_guid/__init__.py validate
